"""followers

Revision ID: 513b4b86093d
Revises: df98af972886
Create Date: 2020-03-08 23:57:01.163579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513b4b86093d'
down_revision = 'df98af972886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.uid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
